[package]
name = "situwaition"
version = "0.0.1"
edition = "2021"
rust_version = "1.70"
authors = [
  "vados <vados@vadosware.io>"
]
categories = [
  "async",
  "utilities",
]

[features]
default = []
tokio = ["dep:tokio"]
async-std = ["dep:async-std"]
mio = ["dep:mio"]

[dependencies]
anyhow = "1.0.71"
mio = { version = "0.8.8", optional = true }
tokio = { version = "1.29.1", optional = true }
async-std = { version = "1.12.0", optional = true }
thiserror = "1.0.40"
