[package]
name = "situwaition-example-async-std"
description = "an example of using situwaition with async-std"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-std = "1.12.0"
situwaition = { path = '../../', features = [ "async-std" ] }
thiserror = "1.0.40"
