name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Setup
      - uses: actions/checkout@v3
      - uses: extractions/setup-just@v1

      # Build
      - name: Build
        run: cargo build --verbose

      # Test
      - name: Run unit tests
        run: just test-unit
      - name: Run integration tests
        run: just test-int
      - name: Run E2E tests
        run: just test-e2e
